- name: variables from files
  hosts: local
  connection: local
  vars_failes: # so here anni files aayina reffer or call cheyachu 
  - course.yaml
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course name is: {{ COURSE }}, Duration is {{ DURATION }}, Trainer name is {{ Trainer }}"