- name: data types
  hosts: local
  connection: local
  vars:
    Course: "DevOps with AWS" # string
    Duration: 120 # number
    is_live: true # boolean
    # list
    tools: # ["linux", "shell", "ansible"] ila ayina pettachu or else like as below 
    - "linux"
    - shell
    - ansible # so ikkada (-) iphen tho start ithe adhi list 
    concepts: # dictionary or map so here below not start with - so we called as map or disctinory
      cloud: aws
      cm: ansible
  tasks:
  - name: print course info
    ansible.builtin.debug: # this the module for excute
      msg: "Course name: {{ Course }}, Duration: {{ Duration }}, is it live?: {{ is_live }}, tools are: {{ tools }} concepts are: {{ concepts }}"

# list: []
# map: {}