- name: functions
  hosts: local
  connection: local
  tasks: 
  - name: default variable
    ansible.builtin.debug:
      # msg: " Hello, {{ name }}" # error is : "The task includes an option with an undefined variable.
      msg: " Hello, {{ name | default('Srikanth') }}"